==================================== INPUT ====================================
# expected-to-throw
query EnabledUserQuery {
  me @catch @catch(to: NULL) {
    id
  }
}
==================================== ERROR ====================================
✖︎ The directive `@catch` can only be used once at this location.

  catch-duplicate-on-same-linked-field.invalid.graphql:3:13
    2 │ query EnabledUserQuery {
    3 │   me @catch @catch(to: NULL) {
      │             ^^^^^^
    4 │     id

  ℹ︎ previously used here

  catch-duplicate-on-same-linked-field.invalid.graphql:3:6
    2 │ query EnabledUserQuery {
    3 │   me @catch @catch(to: NULL) {
      │      ^^^^^^
    4 │     id
